In [27]:
import pandas as pd

data = [['GDP 2019', 21200], ['GDP 2018', 20544.34], ['GDP 2017', 19485.39], ['GDP 2016', 18707.19], ['GDP 2015', 18219.3], \
       ['GDP 2014', 17521.75], ['GDP 2013', 16784.85], ['GDP 2012', 16197.01], ['GDP 2011', 15542.58], ['GDP 2010', 14992.05]]
        
df = pd.DataFrame(data, columns = ['Year', 'USD Billion'])
df

       Year  USD Billion
0  GDP 2019     21200.00
1  GDP 2018     20544.34
2  GDP 2017     19485.39
3  GDP 2016     18707.19
4  GDP 2015     18219.30
5  GDP 2014     17521.75
6  GDP 2013     16784.85
7  GDP 2012     16197.01
8  GDP 2011     15542.58
9  GDP 2010     14992.05

In [8]:
import pandas as pd

data = [['Apr 2020', '14.7%'], ['Mar 2020', '4.4%'], ['Feb 2020', '3.5%'], ['Jan 2020', '3.6%'], ['Dec 2019', '3.5%'], ['Nov 2019', '3.5%'], \
        ['Oct 2019', '3.6%'], ['Sep 2019', '3.5%'], ['Aug 2019', '3.7%'], ['Jul 2019', '3.7%'], ['Jun 2019', '3.7%'], ['May 2019', '3.6%']]

df = pd.DataFrame(data, columns = ['Month', 'Unemployment Rate in %'])
df[0:5]

      Month Unemployment Rate in %
0  Apr 2020                  14.7%
1  Mar 2020                   4.4%
2  Feb 2020                   3.5%
3  Jan 2020                   3.6%
4  Dec 2019                   3.5%

In [17]:
import pandas as pd

data = [['Apr 2020', 14.7], ['Mar 2020', 4.4], ['Feb 2020', 3.5], ['Jan 2020', 3.6], ['Dec 2019', 3.5], ['Nov 2019', 3.5], \
        ['Oct 2019', 3.6], ['Sep 2019', 3.5], ['Aug 2019', 3.7], ['Jul 2019', 3.7], ['Jun 2019', 3.7], ['May 2019', 3.6]]

df = pd.DataFrame(data, columns = ['Month', 'Unemployment Rate in %'])
df

       Month  Unemployment Rate in %
0   Apr 2020                    14.7
1   Mar 2020                     4.4
2   Feb 2020                     3.5
3   Jan 2020                     3.6
4   Dec 2019                     3.5
5   Nov 2019                     3.5
6   Oct 2019                     3.6
7   Sep 2019                     3.5
8   Aug 2019                     3.7
9   Jul 2019                     3.7
10  Jun 2019                     3.7
11  May 2019                     3.6

In [5]:
import pandas as pd

data = [['Apr 2020', 14.7], ['Mar 2020', 4.4], ['Feb 2020', 3.5], ['Jan 2020', 3.6], ['Dec 2019', 3.5], ['Nov 2019', 3.5], \
        ['Oct 2019', 3.6], ['Sep 2019', 3.5], ['Aug 2019', 3.7], ['Jul 2019', 3.7], ['Jun 2019', 3.7], ['May 2019', 3.6]]

df = pd.DataFrame(data, columns = ['Month', 'Unemployment Rate in %'])

df[df['Unemployment Rate in %']>8.5]

      Month  Unemployment Rate in %
0  Apr 2020                    14.7

In [6]:
import pandas as pd
from bokeh.plotting import figure, output_file, show,output_notebook
output_notebook()

In [7]:
def make_dashboard(x, gdp_change, unemployment, title, file_name):
    output_file(file_name)
    p = figure(title=title, x_axis_label='year', y_axis_label='%')
    p.line(x.squeeze(), gdp_change.squeeze(), color="firebrick", line_width=4, legend="% GDP change")
    p.line(x.squeeze(), unemployment.squeeze(), line_width=4, legend="% unemployed")
    show(p)

In [8]:
links={'GDP':'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv',\
       'unemployment':'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'}

In [10]:
filename='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv'

df=pd.read_csv(filename)

df.head()

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [11]:
filename='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'

df=pd.read_csv(filename)

df.head()

   date  unemployment
0  1948      3.750000
1  1949      6.050000
2  1950      5.208333
3  1951      3.283333
4  1952      3.025000

In [13]:
filename1='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'

df1=pd.read_csv(filename1)

df1[df1['unemployment']>8.5]

    date  unemployment
34  1982      9.708333
35  1983      9.600000
61  2009      9.283333
62  2010      9.608333
63  2011      8.933333

In [15]:
filename2='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv'

x=pd.read_csv(filename2)

x.head()

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [24]:
x[['date']]

    date
0   1948
1   1949
2   1950
3   1951
4   1952
5   1953
6   1954
7   1955
8   1956
9   1957
10  1958
11  1959
12  1960
13  1961
14  1962
15  1963
16  1964
17  1965
18  1966
19  1967
20  1968
21  1969
22  1970
23  1971
24  1972
25  1973
26  1974
27  1975
28  1976
29  1977
..   ...
39  1987
40  1988
41  1989
42  1990
43  1991
44  1992
45  1993
46  1994
47  1995
48  1996
49  1997
50  1998
51  1999
52  2000
53  2001
54  2002
55  2003
56  2004
57  2005
58  2006
59  2007
60  2008
61  2009
62  2010
63  2011
64  2012
65  2013
66  2014
67  2015
68  2016

[69 rows x 1 columns]

In [25]:
filename2='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_gdp.csv'

gdp_change=pd.read_csv(filename2)

gdp_change.head()

   date  level-current  level-chained  change-current  change-chained
0  1948          274.8         2020.0            -0.7            -0.6
1  1949          272.8         2008.9            10.0             8.7
2  1950          300.2         2184.0            15.7             8.0
3  1951          347.3         2360.0             5.9             4.1
4  1952          367.7         2456.1             6.0             4.7

In [26]:
gdp_change[['change-current']]

    change-current
0             -0.7
1             10.0
2             15.7
3              5.9
4              6.0
5              0.3
6              8.9
7              5.6
8              5.5
9              1.5
10             8.4
11             4.0
12             3.7
13             7.4
14             5.6
15             7.4
16             8.4
17             9.6
18             5.7
19             9.4
20             8.2
21             5.5
22             8.5
23             9.8
24            11.4
25             8.4
26             9.0
27            11.2
28            11.1
29            13.0
..             ...
39             7.9
40             7.7
41             5.7
42             3.3
43             5.9
44             5.2
45             6.3
46             4.8
47             5.7
48             6.2
49             5.7
50             6.3
51             6.5
52             3.2
53             3.4
54             4.8
55             6.6
56             6.7
57             6.0
58             4.6
59             1.8
60            -1.8
61             3.8
62             3.7
63             4.2
64             3.6
65             4.4
66             4.0
67             2.7
68             4.2

[69 rows x 1 columns]

In [28]:
filename3='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/projects/coursera_project/clean_unemployment.csv'

unemployment=pd.read_csv(filename3)

unemployment.head()

   date  unemployment
0  1948      3.750000
1  1949      6.050000
2  1950      5.208333
3  1951      3.283333
4  1952      3.025000

In [29]:
unemployment[['unemployment']]

    unemployment
0       3.750000
1       6.050000
2       5.208333
3       3.283333
4       3.025000
5       2.925000
6       5.591667
7       4.366667
8       4.125000
9       4.300000
10      6.841667
11      5.450000
12      5.541667
13      6.691667
14      5.566667
15      5.641667
16      5.158333
17      4.508333
18      3.791667
19      3.841667
20      3.558333
21      3.491667
22      4.983333
23      5.950000
24      5.600000
25      4.858333
26      5.641667
27      8.475000
28      7.700000
29      7.050000
..           ...
39      6.175000
40      5.491667
41      5.258333
42      5.616667
43      6.850000
44      7.491667
45      6.908333
46      6.100000
47      5.591667
48      5.408333
49      4.941667
50      4.500000
51      4.216667
52      3.966667
53      4.741667
54      5.783333
55      5.991667
56      5.541667
57      5.083333
58      4.608333
59      4.616667
60      5.800000
61      9.283333
62      9.608333
63      8.933333
64      8.075000
65      7.358333
66      6.158333
67      5.275000
68      4.875000

[69 rows x 1 columns]

In [30]:
title='GDP vs Unemployment'

In [31]:
file_name="index.html"

In [36]:
make_dashboard(x[['date']], gdp_change[['change-current']], unemployment[['unemployment']], title, file_name)